-- Table: public.producto

DROP TABLE IF EXISTS public.producto;

CREATE TABLE IF NOT EXISTS public.producto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    categoria character varying(255) COLLATE pg_catalog."default",
    descripcion character varying(255) COLLATE pg_catalog."default",
    fecha_creacion timestamp(6) without time zone,
    nombre character varying(255) COLLATE pg_catalog."default" NOT NULL,
    precio numeric(38,2),
    CONSTRAINT producto_pkey PRIMARY KEY (id)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.producto
    OWNER to postgres;

-- Table: public.estadistica

DROP TABLE IF EXISTS public.estadistica;

CREATE TABLE IF NOT EXISTS public.estadistica
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cantidad integer NOT NULL,
    categoria character varying(255) COLLATE pg_catalog."default",
    fecha_actualizacion timestamp(6) without time zone,
    CONSTRAINT estadistica_pkey PRIMARY KEY (id)
    )

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.estadistica
    OWNER to postgres;