name: Build and deploy container app to Azure Web App - productosapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'  

   
      - name: Build with Maven
        run: mvn clean install  

     
      - name: List files in target directory
        run: ls -al target/ 


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername }}  
          password: ${{ secrets.AzureAppService_ContainerPassword }}  

      - name: Build and push container image to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .  
          push: true  
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername }}/dockerProductoApp:${{ github.sha }}  # Etiqueta de la imagen Docker
          file: ./Dockerfile 

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'productosapp' 
          slot-name: 'Production'  
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }} 
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername }}/dockerProductoApp:${{ github.sha }}'  # Imagen Docker que será desplegada
